# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bscwt\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from traceback import print_list
from typing import Dict
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

import cv2

#from src.func import run_model, visualize

class Ui_MainWindow(QWidget):

    def __init__(self, mainwindow, Seg):
        super(Ui_MainWindow, self).__init__()

        self.setupUi(mainwindow)
        '''
        TODO: 状态栏，准备中->就绪
        '''
        self.seg = Seg

    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("眼底多病种识别辅助")
        MainWindow.resize(829, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 751, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.AddressEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.AddressEdit.setObjectName("AddressEdit")
        self.horizontalLayout.addWidget(self.AddressEdit)

        self.SelectAddress = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SelectAddress.setObjectName("SelectAddress")
        self.horizontalLayout.addWidget(self.SelectAddress)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 120, 111, 31))
        self.label.setObjectName("label")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 130, 20, 451))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 350, 111, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(286, 350, 51, 31))
        self.label_7.setObjectName("label_7")

        self.diseaseView = QtWidgets.QListView(self.centralwidget)
        self.diseaseView.setGeometry(QtCore.QRect(40, 380, 241, 201))
        self.diseaseView.setObjectName("diseaseView")

        self.orgView = QtWidgets.QLabel(self.centralwidget)
        self.orgView.setGeometry(QtCore.QRect(40, 150, 196, 196))
        self.orgView.setText("")
        self.orgView.setObjectName("orgView")

        self.figureView = QtWidgets.QListView(self.centralwidget)
        self.figureView.setGeometry(QtCore.QRect(280, 380, 61, 201))
        font = QtGui.QFont()
        font.setKerning(False)
        self.figureView.setFont(font)
        self.figureView.setItemAlignment(QtCore.Qt.AlignRight)
        self.figureView.setObjectName("figureView")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(380, 120, 411, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(380, 350, 411, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)

        self.camView = QtWidgets.QLabel(self.centralwidget)
        self.camView.setGeometry(QtCore.QRect(380, 150, 196, 196))
        self.camView.setText("")
        self.camView.setObjectName("camView")
        self.gradView = QtWidgets.QLabel(self.centralwidget)
        self.gradView.setGeometry(QtCore.QRect(590, 150, 196, 196))
        self.gradView.setText("")
        self.gradView.setObjectName("gradView")
        self.gradViewPlus = QtWidgets.QLabel(self.centralwidget)
        self.gradViewPlus.setGeometry(QtCore.QRect(380, 380, 196, 196))
        self.gradViewPlus.setText("")
        self.gradViewPlus.setObjectName("gradViewPlus")
        self.guidedView = QtWidgets.QLabel(self.centralwidget)
        self.guidedView.setGeometry(QtCore.QRect(590, 380, 196, 196))
        self.guidedView.setText("")
        self.guidedView.setObjectName("guidedView")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SelectAddress.clicked.connect(self.main)
        self.diseaseView.clicked.connect(self.getHeatMap)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def main(self):
        
        fname = self.loadImage()
        predict = run_model(fname)
        self.printList(predict)

    def loadImage(self):

        filename, _ = QFileDialog.getOpenFileName(self, '打开文件', '.', '图像文件 (*.jpg *.jpeg *.png *.JPEG)')

        org_img = cv2.imread(filename)
        org_img = cv2.cvtColor(org_img, cv2.COLOR_BGR2RGB)
        org_img = cv2.resize(org_img, (196, 196))
        y, x, _ = org_img.shape

        frame = QImage(org_img, x, y, QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.orgView.setPixmap(pix)

        return filename

    def printList(self, predict: Dict):

        sep = 0
        threshold = 60

        d_lst = []
        f_lst = []
        for idx, (k, v) in enumerate(predict.items()):
            
            if v < threshold:
                if not sep:
                    d_lst.append('=====================')
                    f_lst.append('====')
                    self.sep_idx = idx
                sep += 1

            d_lst.append(k)
            f_lst.append(str(v)+'%')

            if sep == 2:
                break

        d_listModel = QStringListModel()
        d_listModel.setStringList(d_lst)
        self.diseaseView.setModel(d_listModel)

        f_listModel = QStringListModel()
        f_listModel.setStringList(f_lst)
        self.figureView.setModel(f_listModel)

    def getHeatMap(self, item):

        shape = (196, 196)

        if item.row() == self.sep_idx:
            return
        elif item.row() > self.sep_idx:
            idx = item.row() - 1
        else:
            idx = item.row()
        
        cam, gradcam, gradcamp, ggradcam = visualize(idx, shape)
        
        frame = QImage(cam, shape[0], shape[1], QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.camView.setPixmap(pix)

        frame = QImage(gradcam, shape[0], shape[1], QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.gradView.setPixmap(pix)

        frame = QImage(gradcamp, shape[0], shape[1], QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.gradViewPlus.setPixmap(pix)

        frame = QImage(ggradcam, shape[0], shape[1], QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.guidedView.setPixmap(pix)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectAddress.setText(_translate("MainWindow", "输入地址"))
        self.label.setText(_translate("MainWindow", "原始图片"))
        self.label_3.setText(_translate("MainWindow", "GradCAM++"))
        self.label_4.setText(_translate("MainWindow", "GradCAM"))
        self.label_5.setText(_translate("MainWindow", "Guided GradCAM"))
        self.label_2.setText(_translate("MainWindow", "CAM"))
        self.label_6.setText(_translate("MainWindow", "预测结果"))
        self.label_7.setText(_translate("MainWindow", "置信度"))
