# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\clashow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class Ui_ClaShow(QWidget):

    def __init__(self, mainwindow):
        super(Ui_ClaShow, self).__init__()
        self.setupUi(mainwindow)

        self.img = './imgs/cla2.PNG'
        self._load()

    def setupUi(self, ClaShow):
        
        ClaShow.setObjectName("ClaShow")
        ClaShow.resize(978, 586)
        self.centralwidget = QtWidgets.QWidget(ClaShow)
        self.centralwidget.setObjectName("centralwidget")
        self.ClaShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.ClaShowLabel.setGeometry(QtCore.QRect(0, 0, 978, 586))
        self.ClaShowLabel.setText("")
        self.ClaShowLabel.setObjectName("ClaShowLabel")
        ClaShow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClaShow)
        QtCore.QMetaObject.connectSlotsByName(ClaShow)

    def _load(self):
        # import os
        # print(os.path.exists(self.img))
        pixmap = QPixmap(self.img)
        self.ClaShowLabel.setPixmap(pixmap)
        self.ClaShowLabel.setScaledContents(True)

    def retranslateUi(self, ClaShow):
        _translate = QtCore.QCoreApplication.translate
        ClaShow.setWindowTitle(_translate("ClaShow", "多病种分类模型及数据集"))


class Ui_SegShow(QWidget):

    def __init__(self, mainwindow):
        super(Ui_SegShow, self).__init__()
        self.setupUi(mainwindow)

        self.img = './imgs/seg.PNG'
        self._load()

    def setupUi(self, SegShow):
        
        SegShow.setObjectName("SegShow")
        SegShow.resize(929, 586)
        self.centralwidget = QtWidgets.QWidget(SegShow)
        self.centralwidget.setObjectName("centralwidget")
        self.SegShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.SegShowLabel.setGeometry(QtCore.QRect(0, 0, 929, 586))
        self.SegShowLabel.setText("")
        self.SegShowLabel.setObjectName("SegShowLabel")
        SegShow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SegShow)
        QtCore.QMetaObject.connectSlotsByName(SegShow)

    def _load(self):
        # import os
        # print(os.path.exists(self.img))
        pixmap = QPixmap(self.img)
        self.SegShowLabel.setPixmap(pixmap)
        self.SegShowLabel.setScaledContents(True)

    def retranslateUi(self, ClaShow):
        _translate = QtCore.QCoreApplication.translate
        ClaShow.setWindowTitle(_translate("SegShow", "血管视盘分割模型及数据集"))
